In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("students.csv")

In [3]:
data.head()

hours_studied  attendance  previous_score  result
0              1          50              30       0
1              2          55              35       0
2              3          60              40       0
3              4          65              45       0
4              5          70              55       0

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   hours_studied   20 non-null     int64
 1   attendance      20 non-null     int64
 2   previous_score  20 non-null     int64
 3   result          20 non-null     int64
dtypes: int64(4)
memory usage: 772.0 bytes


In [5]:
data.describe()

hours_studied  attendance  previous_score     result
count      20.000000   20.000000       20.000000  20.000000
mean        5.500000   73.600000       59.500000   0.550000
std         2.946898   14.507348       19.140753   0.510418
min         1.000000   50.000000       30.000000   0.000000
25%         3.000000   61.500000       43.750000   0.000000
50%         5.500000   73.500000       59.000000   1.000000
75%         8.000000   85.750000       73.500000   1.000000
max        10.000000   96.000000       90.000000   1.000000

In [6]:
X = data[['hours_studied', 'attendance', 'previous_score']]
y = data['result']

In [7]:
X.shape
y.shape

(20,)

In [8]:
data.isnull().sum()

hours_studied     0
attendance        0
previous_score    0
result            0
dtype: int64

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, 
    test_size=0.2,
    random_state=42
)

In [10]:
from sklearn.linear_model import LogisticRegression

In [11]:
lr = LogisticRegression() 

In [12]:
lr.fit(X_train, y_train)

LogisticRegression()

In [13]:
lr_pred = lr.predict(X_test)

In [14]:
from sklearn.ensemble import RandomForestClassifier

In [20]:
rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=5,
    min_samples_split=4,
    random_state=42
)

In [21]:
rf.fit(X_train, y_train)

RandomForestClassifier(max_depth=5, min_samples_split=4, n_estimators=200,
                       random_state=42)

In [23]:
rf_pred = rf.predict(X_test)

accuracy_score(y_test, rf_pred), confusion_matrix(y_test, rf_pred)


(0.75,
 array([[2, 0],
        [1, 1]]))

In [27]:
print("Logistic Accuracy:", accuracy_score(y_test, lr_pred))
print("Random Forest Accuracy:", accuracy_score(y_test, rf_pred))


Logistic Accuracy: 0.75
Random Forest Accuracy: 0.75


In [25]:
from sklearn.metrics import confusion_matrix

In [26]:
cm_lr = confusion_matrix(y_test, lr_pred)
cm_lr

array([[2, 0],
       [1, 1]])

In [21]:
cm_rf = confusion_matrix(y_test, rf_pred)
cm_rf

array([[2, 0],
       [1, 1]])

In [22]:
def confusion_matrix_manual(y_true, y_pred):
    TP = TN = FP = FN = 0

    for actual, predicted in zip(y_true, y_pred):
        if actual == 1 and predicted == 1:
            TP += 1
        elif actual == 0 and predicted == 0:
            TN += 1
        elif actual == 0 and predicted == 1:
            FP += 1
        elif actual == 1 and predicted == 0:
            FN += 1

    return TP, TN, FP, FN


In [23]:
TP, TN, FP, FN = confusion_matrix_manual(y_test, rf_pred)

print("TP:", TP)
print("TN:", TN)
print("FP:", FP)
print("FN:", FN)

TP: 1
TN: 2
FP: 0
FN: 1


In [24]:
accuracy = (TP + TN) / (TP + TN + FP + FN)
accuracy


0.75

In [25]:
precision = TP / (TP + FP)
precision


1.0

In [26]:
recall = TP / (TP + FN)
recall


0.5

In [27]:
f1 = 2 * (precision * recall) / (precision + recall)
f1


0.6666666666666666

In [28]:
import joblib
joblib.dump(rf, "student_model.pkl")


['student_model.pkl']